7.x 2.x collections soe 2715
SU-SOE/stanford_soe_helper pull request #152
Opened 2018-03-20 15:05 UTC by minorwm

# NOT READY FOR REVIEW

# Summary
- 

# Needed By (Date)
- Sprint end

# Criticality
- Client is eagerly awaiting this.
- Housekeeping
- Fixes broken stuff
- Fixed on prod, need to put into code.

# Steps to Test
- Switch to this branch
- May need to revert feature
- Navigate to __Path__
- Verify you see __Text__

# Affects 
- SoE (School of Engineering website)

# Associated Issues and/or People
## Related JIRA ticket(s)

## Related PRs

## More Information

## Folks to notify
@minorwm

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2018-03-23 16:26 UTC, sherakama requested changes
First pass at code review up. Great job overall but please see the comments.

2018-03-23 16:26 UTC, sherakama commented on README.md
> +##### Version: 7.x-2.0-beta4
Versions should be at `7.x-x.x-dev` until a release tag is cut.

2018-03-23 16:26 UTC, sherakama commented on README.md
> +**[Stanford SoE Helper Collection](https://github.com/SU-SOE/stanford_soe_helper/stanford_soe_helper_collection/)**
Nice! Thank you for the documentation update.

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection/stanford_soe_helper_collection.features.field_base.inc
> +  $field_bases['field_s_collection_cont_label'] = array(
Namespace is good. Thank you.

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection/stanford_soe_helper_collection.features.field_base.inc
> +  $field_bases['field_s_mag_article_collection'] = array(
If this field is on the collection content type it should follow the naming convention that the other fields were using. eg: `field_s_collection_[fieldname]`. Please update.

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection/stanford_soe_helper_collection.features.field_instance.inc
> +          'content_editor_text_format' => 'content_editor_text_format',
This content format is defined in `stanford_jumpstart` but is not listed in the dependencies of the .info file. Please add a dependency to the .info file.

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection/stanford_soe_helper_collection.features.field_instance.inc
> +  $field_instances['node-stanford_magazine_article-field_s_mag_article_collection'] = array(
This is attaching a field to another content type. Please add a dependency to the .info file for stanford_magazine or wherever the content type is stored in a feature.

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection/stanford_soe_helper_collection.features.field_base.inc
> +  $field_bases['field_s_mag_article_collection'] = array(
Ah, I see that this is actually attached to the stanford_magazine content type. Please add a dependency to that module in the .info file.

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection/stanford_soe_helper_collection.features.inc
> +      'name' => t('Collection'),
Thank you for calling this just collection. It is a pet peeve of mine that we call things *`Stanford` Thing* on labels. Machine names should be prefixed with stanford_ often but not labels. Good work here.

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection/stanford_soe_helper_collection.info
> +version = 7.x-2.0-beta4
This should be ` 7.x-2.0-dev` until a tagged release is made.

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection/stanford_soe_helper_collection.info
> +project status url = https://github.com/SU-SOE/stanford_soe_helper.git
Nice addition and attention to detail. This is used with the `erus` module in order to get update status updates from github.

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection_administration/stanford_soe_helper_collection_administration.info
> +version = 7.x-2.0-beta4
should be 7.x-2.0-dev

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection_layouts/stanford_soe_helper_collection_layouts.features.field_base.inc
> +function stanford_soe_helper_collection_layouts_field_default_field_bases() {
Why are these exported here instead of in stanford_soe_helper_collection?

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection_layouts/stanford_soe_helper_collection_layouts.info
> +version = 7.x-2.0-beta4
should be -dev

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection_layouts/stanford_soe_helper_collection_layouts.info
> +dependencies[] = bean
missing xmlsitemap dependency

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection_layouts/stanford_soe_helper_collection_layouts.info
> +dependencies[] = bean
Missing pathauto dependency

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection_views/stanford_soe_helper_collection_views.info
> +version = 7.x-2.0-beta4
should be `-dev`

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection_views/stanford_soe_helper_collection_views.views_default.inc
> +  $handler->display->display_options['query']['options']['disable_sql_rewrite'] = TRUE;
Why is this disabled? Doesn't this then cause this view to bypass the access and permissions hooks when fetching content?

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection_views/stanford_soe_helper_collection_views.views_default.inc
> +    'image_style' => '6-col-banner-short',
Missing dependency on stanford_image_styles in your .info file for this

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection_views/stanford_soe_helper_collection_views.views_default.inc
> +    'stanford_magazine_article' => 'stanford_magazine_article',
Missing dependency on stanford_magazine_article in the .info file.

2018-03-23 16:26 UTC, sherakama commented on modules/stanford_soe_helper_collection_views/stanford_soe_helper_collection_views.views_default.inc
> +  $handler->display->display_options['header']['area']['content'] = '<h1>Stanford Engineering Magazine</h1>
Why is the page title in the header area? Does the normal page title not look right?

2018-03-23 16:26 UTC, sherakama commented on scss/components/_soe_dm_collection.scss
> +      display: none;
I am not a fan of hiding titles with display: none. Robots and screen readers can still pick these up sometimes. Also, it causes problems for the next developer with discoverability. When they go to change the page title with a hook_alter or something else it wont visibly take effect causing troubleshooting time and overhead that could be avoided. I would like you to find a different approach to the page title. 

Why do you need to provide your own in the view?

2018-03-23 16:26 UTC, sherakama commented on stanford_soe_helper.info
> +version = 7.x-2.0-beta4
This should be `-dev`

2018-03-26 22:23 UTC, minorwm commented
@sherakama I have made the edits and this is ready for you to review again.

2018-03-27 20:30 UTC, minorwm commented
@sherakama This is ready for your review.

2018-03-27 22:19 UTC, sherakama requested changes
Just one missing dependency and a version to go. 

Thats it. All the new work looks fine.

2018-03-27 22:19 UTC, sherakama commented on modules/stanford_soe_helper_collection/stanford_soe_helper_collection.features.field_instance.inc
> +          'content_editor_text_format' => 'content_editor_text_format',
@minorwm This is still missing. Please add the dependency.

2018-03-27 22:19 UTC, sherakama commented on stanford_soe_helper.info
> -version = 7.x-2.0-beta3
Missed this.

2018-03-27 22:38 UTC, minorwm commented
@sherakama those are fixed

2018-03-27 22:50 UTC, sherakama approved these changes

2018-03-27 22:57 UTC, merged