SOE-3477: added Image Caption CSS
SU-SOE/stanford_soe_helper pull request #220
Opened 2018-09-12 19:40 UTC by cjwest

# NOT READY FOR REVIEW

# Summary
_See ticket: https://stanfordits.atlassian.net/browse/SOE-3477_
This adds styles so we can have captions on images in the WYSIWYG

# Needed By (Date)
- Code Freeze

# Criticality
- Client is eagerly awaiting this.

# Steps to Test
## Check out this branch
`git checkout 7.x-2.x-SOE-3446-caption`

## Add `caption` styles to WYSIWYG filter at: `admin/config/content/wysiwyg/profile/content_editor_text_format/edit`

```
Image Caption Right=div.image-caption-right
Image Caption Left=div.image-caption-left
```

Add to **Rules for class names** at: `admin/config/content/formats/content_editor_text_format`

```
image-caption-right,
image-caption-left
```

# Affects 
- SoE (School of Engineering website)

# Associated Issues and/or People
## Related JIRA ticket(s)
PR: https://stanfordits.atlassian.net/browse/SOE-3477
Documentation & Discussion: https://stanfordits.atlassian.net/browse/SOE-3446

## Related PRs

## More Information

## Folks to notify
`@annawatt `
`@kerri-augenstein `

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2018-09-13 22:24 UTC, minorwm requested changes
@cjwest I'm not seeing where to insert an image in the wysiwyg. Can you please provide more information and/or a screenshot for this?

2018-09-13 22:41 UTC, cjwest commented
If Kerri is around she can show you

Sent from my iPhone

On Sep 13, 2018, at 3:24 PM, Bill Minor <notifications@github.com<mailto:notifications@github.com>> wrote:


@minorwm requested changes on this pull request.

@cjwest<https://github.com/cjwest> I'm not seeing where to insert an image in the wysiwyg. Can you please provide more information and/or a screenshot for this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/SU-SOE/stanford_soe_helper/pull/220#pullrequestreview-155295179>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AARXGIAFCuTcvUl7ND_9IiW4GJAYNKBiks5uatsOgaJpZM4WmCX1>.

2018-09-14 14:05 UTC, minorwm commented
@cjwest I figured it out. It helps to read the help text when inserting an image on the wysiwyg. Everything looks good to me.

2018-09-14 14:05 UTC, minorwm approved these changes

2018-09-14 14:05 UTC, merged